### ISSUE TITLE
NullPointerException when trying to "press" submit button the second time during authentication

### ISSUE THREAD

**Issue by ANicholasson** [PersonligFrelser/bb-discord-announcer#11]
The exception occurs here:
` // FEIDE requires pressing the submit button after submission (because of javscript issues)
        client.waitForBackgroundJavaScript(5000);
        page = ((HtmlSubmitInput) page.getElementById("postLoginSubmitButton")).click();`

I believe this is because blackboard has removed the id on the button as shown below: 
`<button type="submit" class="button-primary breathe-top">Logg inn</button>`

**Comment by libanbn** [comment]
Issue fixed in ab59169 as the NTNU Blackboard Scraper no longer uses FEIDE to authenticate student accounts
