### ISSUE TITLE
The NTNU Blackboard Scraper can't fetch the author of the announcement

### ISSUE THREAD

**Issue by libanbn** [PersonligFrelser/bb-discord-announcer#14]
The DOM elements from where the announcement is gathered from does not include who pushed the announcement.

**Comment by ANicholasson** [comment]
Maybe ignore the person that pushed the assignment? The announcement is there, with the course name and ID. The author of that announcement ain't that important? @PersonligFrelser

**Comment by libanbn** [comment]
The issue is fixed fbc86e253d10bb2d58d9cc5a15542962c302cbac
