### ISSUE TITLE
The NTNU Blackboard Scraper is not converting announcement the date to timestamp

### ISSUE THREAD

**Issue by libanbn** [PersonligFrelser/bb-discord-announcer#15]
See https://github.com/PersonligFrelser/bb-discord-announcer/blob/ab591697245451970e736f9c86a53e80f2fbb20c/src/main/java/app/NtnuBlackboardScraper.java#L125

**Comment by ANicholasson** [comment]
The "date" extracted from the announcement is of type string: "5 days ago". We should either just use this value or we can take todays date minus the n of n days ago. Then we would have had to make something like this if the announcement is over a month old: "n.04.2020" since n is unknown @PersonligFrelser

**Comment by libanbn** [comment]
There are multiple ways this can be done. The simplest one is to parse that string into a UNIX timestamp and leave it with an inaccuracy of 1 month. Another method is to call to another page that has more details about the announcement.

The URL of the announcement details can be seen here:
![1](https://user-images.githubusercontent.com/33696780/82833072-4d3be580-9ebd-11ea-881e-236e43445d21.png)

And the extra details are:

![2](https://user-images.githubusercontent.com/33696780/82833107-68a6f080-9ebd-11ea-8e1c-ef8630b4571e.png)

You can choose which method you want to use. The goal is to one day migrate from scraping to using the Blackboard API which supplies us with much more information.

**Comment by ANicholasson** [comment]
But BB doesn't have an API for that sort of data?

**Comment by libanbn** [comment]
The API has weird behaviours and it's result are not consistent. I'm currently experimenting with it and it may be working here #24

**Comment by libanbn** [comment]
The issue is fixed fbc86e253d10bb2d58d9cc5a15542962c302cbac
